"""Add required skills to jobs

Revision ID: 6f3a3191fd44
Revises: db51b971b426
Create Date: 2026-08-19 15:59:56.599211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3a3191fd44'
down_revision: Union[str, Sequence[str], None] = 'db51b971b426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_skills', sa.String(length=255), nullable=True))
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('jobs', 'required_skills')
    # ### end Alembic commands ###
